name: Cut release

on:
  push:
    branches: [publish]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up NPM 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Compile
        run: sbt compile
      - name: Run tests
        run: sbt test
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Create release tag file
        run: sbt createReleaseTag
      - name: Set release tag env variable
        run: cat tag.txt >> $GITHUB_ENV
      - name: Check tag
        run: echo "${{ env.RELEASE_TAG }}"