name: Scala CI

on:
  push:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up NPM 16
      uses: actions/setup-node@v3
      with:
        node-version: "16"
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
    - name: Make a local publishing
      run: sbt publishLocal
